### PR TITLE
Sign-up functionality

### LINKED ISSUE #4: Sign Up Route

### PR DESCRIPTION
**Pull request by brandonLi8**
# Contributors
@brandonLi8 

# Reviewers
@anjanbharadwaj 
@teekenzie

# Relevant issue
Closes #4

# Summary of change
- Added auth router
- Added auth controller
- Added register method in the controller
   + used bcrypt to encrypt the password
   + added check to ensure same email is not added twice

# Testing
- Manually tested. We will talk about written tests later.
- Sample curl call (confirmed push on mongodb)
```
- curl --location --request POST 'localhost:8080/auth/register' \
--header 'Content-Type: application/json' \
--data-raw '{
    "name": "Test",
    "age": 10,
    "email_address": "Test@Test.com",
    "passsword": "TestPassword"
}'
```
 - Confirmed 400 response when the same email is registered twice.

### CODE REVIEW

**Comment by teekenzie** [comment]
Can you run make clean real quick to format and tidy up the dependencies

You don't need to create a new User struct. First, bind the body to models.User instead of IRegister. The body variable that you had could then be passed into creation, you would just need to edit the password right before passing it in. 

Instead of using SimpleFind, use mgm.First. (First is a more appropriate method in this situation)

**Comment by brandonLi8** [comment]
> You don't need to create a new User struct. First, bind the body to models.User instead of IRegister. The body variable that you had could then be passed into creation, you would just need to edit the password right before passing it in.

@teekenzie I'm not sure this is the way to go. Firstly, the types don't flow well together, since `models.User` does not implement `mgm.Mode`. You can't pass `models.User` into `mgm.coll` or `mgm.Create` . Also if I do that, the body json would be upper case (which isn't the convention).

**Comment by brandonLi8** [comment]
> Instead of using SimpleFind, use mgm.First. (First is a more appropriate method in this situation)

Done

> Can you run make clean real quick to format and tidy up the dependencies

Done

Back to @teekenzie.

**Review by anjanbharadwaj — APPROVED** [review]
Regarding the IRegister struct and its usage, I think I agree with Brandon here - it would be unnatural for the JSON keys to be capitalized. Plus, I think it's in our best interest to get these early PRs merged in ASAP (since a lot of future PRs rely on this "baseline" code getting merged into master, e.g. my Login code). Maybe we can merge for now, and take a look a bit later and I'm sure we can find a quick fix then?

**Comment by teekenzie** [comment]
> @teekenzie I'm not sure this is the way to go. Firstly, the types don't flow well together, since `models.User` does not implement `mgm.Mode`. You can't pass `models.User` into `mgm.coll` or `mgm.Create` . Also if I do that, the body json would be upper case (which isn't the convention).

Regarding the issue of types, model.User is mgm.Model. If you notice, when I define the struct, the first line starts with mgm.DefaultModel, which somehow just makes it a mgm.Model. 

On the issue of json, we could include annotation for the struct defined in models. 

The reason why I would like to combine them is because I am seeing a lot of field we got to mange. Let's say one day we decided to get rid of the field email, I see many places where we would have to change it and that's very prune to issue

**Comment by brandonLi8** [comment]
> Regarding the issue of types, model.User is mgm.Model. If you notice, when I define the struct, the first line starts with mgm.DefaultModel, which somehow just makes it a mgm.Model. <br>
On the issue of json, we could include annotation for the struct defined in models.<br>
The reason why I would like to combine them is because I am seeing a lot of field we got to mange. Let's say one day we decided to get rid of the field email, I see many places where we would have to change it and that's very prune to issue

Nice.

**Pull request merged**
