### PR TITLE
Feat/#6

### LINKED ISSUE #6: Create the User Model
From #1 (splitting it up into smaller sub-tickets), create the user model. Needed for login/sign-up

### PR DESCRIPTION
**Pull request by teekenzie**
# Contributors
@teekenzie 

# Reviewers
@brandonLi8 
@aidenszeto 

# Relevant issue
Closes #6 

# Summary of change
- Created user model

# Testing
- n/a

### CODE REVIEW

**Review by brandonLi8 — APPROVED** [review]
Looks good! We can talk about the university field later.

**Review by aidenszeto — CHANGES_REQUESTED** [review]
Looks solid. Here's some other fields we could discuss and consider adding:
 - `PastDrifts` - array of drift object IDs that the User has participated in
 - `Friends` - array of user object IDs that the User is friends with
 - `Username` - string indicating User's unique username; it might be preferable for users to be identified by username rather than email
 - `FriendRequests` - array of user object IDs that indicate the User's pending friend requests
 - `CurrentDrift` - object including status on whether or not the User is currently in a drift, along with the drift's object ID

**Comment by brandonLi8** [comment]
> Looks solid. Here's some other fields we could discuss and consider adding:
    PastDrifts - array of drift object IDs that the User has participated in
    Friends - array of user object IDs that the User is friends with
    Username - string indicating User's unique username; it might be preferable for users to be identified by username rather than email
    FriendRequests - array of user object IDs that indicate the User's pending friend requests
    CurrentDrift - object including status on whether or not the User is currently in a drift, along with the drift's object ID

Agreed. @aidenszeto lets maybe include that for #1? This was meant to be a small ticket so we can start login/sign-up.

**Comment by aidenszeto** [comment]
> > Looks solid. Here's some other fields we could discuss and consider adding:
> > PastDrifts - array of drift object IDs that the User has participated in
> > Friends - array of user object IDs that the User is friends with
> > Username - string indicating User's unique username; it might be preferable for users to be identified by username rather than email
> > FriendRequests - array of user object IDs that indicate the User's pending friend requests
> > CurrentDrift - object including status on whether or not the User is currently in a drift, along with the drift's object ID
> 
> Agreed. @aidenszeto lets maybe include that for #2? This was meant to be a small ticket so we can start login/sign-up.

Sounds good I'll make a ticket to expand on the User Model. Let's just merge this in so we have a basis for the mgm models too.

**Review by aidenszeto — APPROVED** [review]

**Comment by aidenszeto** [comment]
@teekenzie Should be good for a merge

**Pull request merged**
